# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This will overwrite the llm_api_config.yaml

# TODO: Specifying the context and generation servers in the config file is
# bit confusing. Investigate if we can clean this up.

hostname: localhost
port: 8080
trust_remote_code: true
backend: pytorch

context_servers:
  num_instances: 1
  tensor_parallel_size: 1
  max_num_tokens: 10240
  max_batch_size: 16
  enable_chunked_prefill: false
  kv_cache_config:
    free_gpu_memory_fraction: 0.40
  pytorch_backend_config:
    enable_overlap_scheduler: false
    use_cuda_graph: false
  urls:
      - "localhost:8001"

generation_servers:
  num_instances: 1
  tensor_parallel_size: 1
  max_num_tokens: 256
  max_batch_size: 256
  kv_cache_config:
    free_gpu_memory_fraction: 0.40
  pytorch_backend_config:
    enable_overlap_scheduler: true
    use_cuda_graph: false
  urls:
      - "localhost:8002"